"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _right_bar from './right-bar.bones.json'

registerBones({
  "right-bar": _right_bar,
})
